In [2]:
### Import Numpy as np
import numpy as np

In [3]:
 np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [10]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
reverse_vector = vector[::-1]

print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [15]:
array = np.arange(9)
matrix = np.reshape(array, (3, 3))

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
indices = np.nonzero(array)

print(indices)

(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [17]:
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
row = np.arange(5)

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(row, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [19]:
vector = np.linspace(0, 1, 12, endpoint=True)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [20]:
vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(vector)

print(sorted_vector)

[0.11417616 0.16777568 0.24871313 0.28108476 0.39305172 0.51178714
 0.52784202 0.58162493 0.67308284 0.96950743]


In [21]:
for dtype in [np.int8, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}")

# Floating-point types
for dtype in [np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min = {info.min}, max = {info.max}, eps = {info.eps}")

<class 'numpy.int8'>: min = -128, max = 127
<class 'numpy.int32'>: min = -2147483648, max = 2147483647
<class 'numpy.int64'>: min = -9223372036854775808, max = 9223372036854775807
<class 'numpy.float32'>: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38, eps = 1.1920928955078125e-07
<class 'numpy.float64'>: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308, eps = 2.220446049250313e-16


In [22]:
array = np.random.rand(10).astype(np.float32)

print("Original array:")
print(array)

# Convert the array to int32 in place
array = array.astype(np.int32)

print("Array after conversion:")
print(array)


Original array:
[0.89817697 0.47810203 0.14862083 0.54475915 0.58843976 0.71569985
 0.5444485  0.07845476 0.4714025  0.53860265]
Array after conversion:
[0 0 0 0 0 0 0 0 0 0]


In [23]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the mean from each row
matrix = matrix - row_means.reshape(-1, 1)

print(matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [24]:
# Create a 2D array
matrix = np.array([[1, 6, 3], [4, 5, 9], [7, 2, 8]])

print("Original matrix:")
print(matrix)

# Choose a column to sort by
n = 1  # Second column

# Get the indices that would sort the nth column
indices = np.argsort(matrix[:, n])

# Sort the matrix by the nth column
sorted_matrix = matrix[indices]

print("Matrix sorted by the nth column:")
print(sorted_matrix)




Original matrix:
[[1 6 3]
 [4 5 9]
 [7 2 8]]
Matrix sorted by the nth column:
[[7 2 8]
 [4 5 9]
 [1 6 3]]


In [25]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original matrix:")
print(matrix)

# Swap the first and second rows
matrix[[0, 1]] = matrix[[1, 0]]

print("Matrix after swapping the first and second rows:")
print(matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after swapping the first and second rows:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [26]:
# Given bincount
C = np.array([2, 3, 1, 0, 2])

# Produce an array such that np.bincount(A) == C
A = np.repeat(np.arange(len(C)), C)

print(A)



[0 0 1 1 1 2 4 4]
